[tox]
min_version = 4.0
env_list = lint, unit

[testenv]
set_env =
    PYTHONPATH = {tox_root}/src:{tox_root}/lib

[testenv:lint]
description = Check code style and type hints
deps =
    ruff
commands =
    ruff check src/ tests/
    ruff format --check src/ tests/

[testenv:fmt]
description = Auto-fix formatting
deps =
    ruff
commands =
    ruff format src/ tests/
    ruff check --fix src/ tests/

[testenv:unit]
description = Run unit tests
deps =
    pytest
    pytest-cov
    ops[testing]
    pyyaml
commands =
    pytest {tty:--color=yes} \
        --tb=short \
        --cov=src \
        --cov-report=term-missing \
        tests/unit/ \
        {posargs}
